web/modules/custom/charges_slip/src/Controller/ChargesSlipDesignController.php
<?php

namespace Drupal\charges_slip\Controller;

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\field\Entity\FieldConfig;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Class ChargesSlipDesignController.
 */
class ChargesSlipDesignController extends ControllerBase
{

    public function slipDesign()
    {

        $build = [
            '#theme' => 'slip_design',
            '#attached' => [
                'library' => [
                    'charges_slip/slip-styles',
                ]
            ]
        ];

        $build['#cache']['max-age'] = 0;

        return $build;
    }

    public function getPatientDetails()
    {

        $patient = array();

        $pcode = \Drupal::request()->query->get('id');

        $query = \Drupal::entityQuery('node');
        $query->condition('type', 'patient')
            ->condition('field_patient_code', $pcode);
        $entity_ids = $query->execute();
        $pid = reset($entity_ids);

        $patientDetails = Node::load($pid);

        if ($patientDetails != NULL) {

            $query = \Drupal::entityQuery('node');
            $query->condition('type', 'payment_due')
                ->condition('field_patient', $pid)
                ->condition('field_status', 'u');
            $entity_ids = $query->execute();

            $did = reset($entity_ids);
            $due = Node::load($did);

            $patient['old_due_amount'] = $due->field_amount_due->value;
            $patient['patient_name'] = $patientDetails->getTitle();
            $patient['patient_address'] = $patientDetails->field_address->value;
            $patient['phone_mobile'] = $patientDetails->field_phone_number->value;
            $patient['age'] = $patientDetails->field_age->value;
            $patient['sex'] = $patientDetails->field_sex->value;
            $patient['patient_id'] = $pid;

        }

        return new JsonResponse($patient);
    }

    public function getDepartment()
    {
        $did = \Drupal::request()->query->get('id');
        $doc = Node::load($did);
        $deptId = $doc->field_department->target_id;
        $term = Term::load($deptId);
        $dept = $term->getName();
        return new JsonResponse($dept);
    }

    public function getDoctorsList()
    {

        $doc = array();

        $query = \Drupal::entityQuery('node');
        $query->condition('type', 'doctor');
        $dids = $query->execute();

        foreach ($dids as $did) {
            $d = Node::load($did);
            $nm = $d->getTitle();
            $doc[$did] = $nm;
        }

        return new JsonResponse($doc);
    }

    public function getServiceList()
    {

        $properties['name'] = 'service';
        $terms = \Drupal::service('entity_type.manager')
            ->getStorage("taxonomy_term")
            ->loadTree('service', $parent = 0, $max_depth = NULL, $load_entities = FALSE);

        $services = array();

        for ($i = 0; $i < sizeof($terms); $i++) {
            $services[$terms[$i]->tid] = $terms[$i]->name;
        }

        return new JsonResponse($services);
    }

    public function generateTransaction()
    {

        $patientId = $_POST['patient_id'];
        $patientDetails = Node::load($patientId);

        $pid = -1;

        if ($patientDetails == NULL) {

            $patientName = $_POST['patient_name'];
            $patientAdd = $_POST['patient_address'];
            $patientPh = $_POST['phone_mobile'];
            $patientAge = $_POST['age'];
            $patientSex = $_POST['sex'];
            $patientCode = $_POST['patient_code'];

            $nids = \Drupal::entityQuery('node')->condition('type', 'patient')->execute();

            $flag = 1;
            foreach ($nids as $key => $value) {
                $node = Node::load($key);
                $pc = $node->field_patient_code->value;
                if ($pc == $patientCode) {
                    $flag = 0;
                    break;
                }
            }

            if ($flag) {
                $node = Node::create([
                    'type' => 'patient',
                    'title' => $patientName,
                    'field_address' => $patientAdd,
                    'field_age' => $patientAge,
                    'field_phone_number' => $patientPh,
                    'field_sex' => $patientSex,
                    'field_patient_code' => $patientCode,
                ]);
                $node->save();
                $pid = $node->id();
                drupal_set_message('Patient created Successfully');
            } else {
                drupal_set_message('Patient Code Already Exists', 'error');
                $response = new RedirectResponse('/slip');
                $response->send();
                return;
            }


        }

        if ($pid == -1)
            $pid = $_POST['patient_id'];

        $tdate = explode(' ', DrupalDateTime::createFromTimestamp(time()));

        $node = Node::create([
            'type' => 'transaction',
            'title' => 'Sample Transaction',
            'field_prescription_number' => $_POST['prescription_no'],
            'field_doctor' => $_POST['doctor_name'],
            'field_patient' => $pid,
            'field_cash_paid' => $_POST['cash_paid'],
            'field_transaction_type' => 'Doctor\'s Consultant',
            'field_transaction_date' => $tdate,
            'field_narration' => $_POST['narration'],
            'field_blood_pressure' => $_POST['bp'],
            'field_blood_sugar_fasting' => $_POST['bs_fs'],
            'field_blood_sugar_pp' => $_POST['bs_pp'],
            'field_blood_sugar_random' => $_POST['bs_rn'],
        ]);
        $node->save();
        $tid = $node->id();

        $node = Node::load((int)$node->id());
        $field = FieldConfig::load('node.transaction.field_sl_no');
        $serialStorage = \Drupal::getContainer()->get('serial.sql_storage');
        $serial = $serialStorage->generateValue($field, $node);
        $node->set('field_sl_no', $serial);

        if($_POST['cash_paid'] > 0){

            $field2 = FieldConfig::load('node.transaction.field_receipt_no');
            $serialStorage2 = \Drupal::getContainer()->get('serial.sql_storage');
            $serial2 = $serialStorage2->generateValue($field2, $node);
            $node->set('field_receipt_no', $serial2);
            $node->set('field_slip_generated', 1);

        }
        else{
            $node->set('field_slip_generated', 0);
        }

//        if (isset($_POST['generate_slip'])) {
//
//            $field2 = FieldConfig::load('node.transaction.field_receipt_no');
//            $serialStorage2 = \Drupal::getContainer()->get('serial.sql_storage');
//            $serial2 = $serialStorage2->generateValue($field2, $node);
//            $node->set('field_receipt_no', $serial2);
//            $node->set('field_slip_generated', 1);
//
//        } else {
//            $node->set('field_receipt_no', $_POST['receipt_no']);
//            $node->set('field_slip_generated', 0);
//        }

        $node->save();

        $tid = $node->id();

        if ($_POST['due'] > 0) {

            $query = \Drupal::entityQuery('node');
            $query->condition('type', 'payment_due')
                ->condition('field_patient', $pid)
                ->condition('field_status', 'u');
            $entity_ids = $query->execute();

            if (sizeof($entity_ids) > 0) {
                $did = reset($entity_ids);
                $due = Node::load($did);
                $due->field_status->value = 'p';
                $due->save();
                $node = Node::create([
                    'type' => 'payment_due',
                    'field_amount_due' => $_POST['due'],
                    'field_patient' => $pid,
                    'field_transaction' => $tid,
                ]);
                $node->save();
                drupal_set_message('Payment Due Added');
            } else {
                $node = Node::create([
                    'type' => 'payment_due',
                    'field_amount_due' => $_POST['due'],
                    'field_patient' => $pid,
                    'field_status' => 'u',
                    'field_transaction' => $tid,
                ]);
                $node->save();
                drupal_set_message('Payment Due Added');
            }
        }

        if ($_POST['due'] == "" || $_POST['due'] == "0") {


            $query = \Drupal::entityQuery('node');
            $query->condition('type', 'payment_due')
                ->condition('field_patient', $pid)
                ->condition('field_status', 'u');
            $entity_ids = $query->execute();

            if (sizeof($entity_ids) > 0) {
                $did = reset($entity_ids);
                $due = Node::load($did);
                $due->field_status->value = 'p';
                $due->save();
                drupal_set_message('Payment Due Cleared');
            }
        }

        $total = 0;
        if ($_POST['select_service'] != '') {
            $select_services = json_decode($_POST['select_service'], 1);

            foreach ($select_services as $select_service) {

                if(sizeof($select_service)>0){

                    $node = Node::create([
                        'type' => 'transaction_service',
                        'title' => 'Sample Transaction',
                        'field_service' => $select_service['service_id'],
                        'field_transaction' => $tid,
                        'field_base_amount' => $select_service['base_amount'],
                        'field_service_count' => $select_service['count'],
                        'field_amount' => $select_service['amount'],
                    ]);
                    $node->save();

web/modules/custom/charges_slip/templates/check-whitelist.html.twig
<h1 id="msg" style="display: none">Redirecting.</h1>
<script src="/modules/custom/charges_slip/assets/js/sweetalert2.all.js"></script>
<script>
    swal({
        title: 'Verify',
        input: 'password',
        inputPlaceholder:'Enter password here',
        showCancelButton: true,
        confirmButtonText: 'Submit',
        allowOutsideClick: false,
        showLoaderOnConfirm: true,
        preConfirm: (password) => {
            return new Promise((resolve) => {
                if (password === '') {
                    swal.showValidationError(
                        'Please enter password first.'
                    );
                    resolve()
                }
                if(password){
                    let url = "/whitelist";
                    let nid = {{ data.nid }};
                    jQuery('<form action="'+url+'" method="post">' +
                        '<input type="hidden" name="pass" value="'+password+'" />'+
                        '<input type="hidden" name="nid" value="'+nid+'" />'+
                        '</form>').appendTo('body').submit();
                }
            })
        },
    }).then((result) => {
        if (!result.value) {
            jQuery("#msg").css({display:'block'});
            let c = 0;
            setInterval(function () {
                if(c<2){
                    jQuery("#msg").html(jQuery("#msg").text()+".");
                    c = c +1;
                }
                else {
                    jQuery("#msg").html('Redirecting.');
                    c = 0;
                }
            },500);
            window.location.href = "/payment-due";
        }
    });
</script>

web/modules/custom/charges_slip/templates/doctor-wise.html.twig
<h1 style="color: #000;">SEVA BHARTI (NEW ALIPORE) TRUST</h1>
<div class="filter-wrapper">
    {% set u = url('<current>')['#markup']|split('/') %}
    {% set u = u|last %}
    <form id="filter-form" action="{{ u }}" method="get">
        <div class="form-group">
            From: <input type="text" class="date" name="fromDate" value="{{ data.fromDate }}">
        </div>
        <div class="form-group">
            To: <input type="text" class="date" name="toDate" value="{{ data.toDate }}">
        </div>
        <div class="form-group">
            <input type="submit" value="Filter" class="btn"/>
            <a href="{{ u }}" class="btn">Reset</a>
        </div>
    </form>
</div>

<div id="main-table">

    <div class="period">
        {% if data.fromDate == '' %}
            {% if data.toDate == '' %}
                <h3>PERIOD till {{ "now"|date("d-m-Y") }}</h3>
            {% else %}
                <h3>PERIOD till {{ data.toDate|date("d-m-Y") }}</h3>
            {% endif %}
        {% else %}
            {% if data.toDate == '' %}
                <h3>PERIOD FROM {{ data.fromDate|date("d-m-Y") }} to {{ "now"|date("d-m-Y") }}</h3>
            {% else %}
                <h3>PERIOD FROM {{ data.fromDate|date("d-m-Y") }} to {{ data.toDate|date("d-m-Y") }}</h3>
            {% endif %}
        {% endif %}
    </div>

    <div style="display:flex;margin-top:-10px;">
        <h4>Serial no: From {{ data.first_sl_no }} to {{ data.last_sl_no }}</h4>
        <h4 style=" margin-left: 16px">Receipt no: From {{ data.first_receipt_no }} to {{ data.last_receipt_no }}</h4>
    </div>

    <table>
        <tr class="table-header">
            <th>DEPARTMENT</th>
            <th>DOCTOR</th>
            <th>NO OF PATIENT</th>
            <th>RECEIVED</th>
        </tr>
        {% for transaction in data.transactions %}
            <tr>
                <td>{{ transaction.department }}</td>
                <td>{{ transaction.doctor }}</td>
                <td>{{ transaction.patient }}</td>
                <td>{{ transaction.amount }}</td>
            </tr>
        {% endfor %}
        <tr class="table-total" style="font-weight: bold; ">
            <td>TOTAL</td>
            <td>{{ data.transactions|length }}</td>
            <td>{{ data.total_patient }}</td>
            <td>{{ data.total_amt }}</td>
        </tr>
    </table>
</div>
<input type="button" id="print-button" value="Print">

web/modules/custom/charges_slip/templates/edit-permission-validate.html.twig
<h1 id="msg" style="display: none">Redirecting.</h1>
<script src="/modules/custom/charges_slip/assets/js/sweetalert2.all.js"></script>
<script>
    swal({
        title: 'Verify',
        input: 'password',
        inputPlaceholder:'Enter password here',
        showCancelButton: true,
        confirmButtonText: 'Submit',
        allowOutsideClick: false,
        showLoaderOnConfirm: true,
        preConfirm: (password) => {
            return new Promise((resolve) => {
                if (password === '') {
                    swal.showValidationError(
                        'Please enter password first.'
                    );
                    resolve()
                }
                if(password){
                    let url = "/edit-transaction-form";
                    let nid = {{ data.nid }};
                    jQuery('<form action="'+url+'" method="post">' +
                        '<input type="hidden" name="pass" value="'+password+'" />'+
                        '<input type="hidden" name="nid" value="'+nid+'" />'+
                        '</form>').appendTo('body').submit();
                }
            })
        },
    }).then((result) => {
        if (!result.value) {
            jQuery("#msg").css({display:'block'});
            let c = 0;
            setInterval(function () {
                if(c<2){
                    jQuery("#msg").html(jQuery("#msg").text()+".");
                    c = c +1;
                }
                else {
                    jQuery("#msg").html('Redirecting.');
                    c = 0;
                }
            },500);
            window.location.href = "/transaction-details";
        }
    });
</script>

web/modules/custom/charges_slip/templates/edit-transaction-form.html.twig
<head>
    <link rel="stylesheet" href="/modules/custom/charges_slip/assets/css/jquery-ui.css">
    <script src="/modules/custom/charges_slip/assets/js/jquery.min.js"></script>
    <script src="/modules/custom/charges_slip/assets/js/jquery-ui.js"></script>
</head>
<style>
    .form-row{
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        margin-top: 5px;
        border: 1px solid #e2e2e2;
        padding: 5px;
    }
    .form-row > .form-group{
        margin-right: 10px;
    }
    .form-group > input{
        height: 22px;
    }

    .login-loader.is-active {
        display: flex;
        justify-content: center;
        align-items: center;
        position: fixed;
        z-index: 9999;
        background-color: rgba(0, 0, 0, 0.50);
        height: 100vh;
        width: 100vw;
        top: 0;
        left: 0;
    }

    .login-loader{
        display: none;
    }

    .lds-ring {
        display: inline-block;
        position: relative;
        width: 64px;
        height: 64px;
    }

    .lds-ring div {
        box-sizing: border-box;
        display: block;
        position: absolute;
        width: 51px;
        height: 51px;
        margin: 6px;
        border: 6px solid #fff;
        border-radius: 50%;
        animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
        border-color: #fff transparent transparent transparent;
    }

    .lds-ring div:nth-child(1) {
        animation-delay: -0.45s;
    }

    .lds-ring div:nth-child(2) {
        animation-delay: -0.3s;
    }

    .lds-ring div:nth-child(3) {
        animation-delay: -0.15s;
    }

    @keyframes lds-ring {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>
<div class="login-loader is-active">
    <div class="lds-ring">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<h1>Edit Transaction</h1>
<form action="/edit-transaction-form" id="edit-form" method="post">
    <input type="hidden" name="isEdit" value="true">
    <input type="hidden" name="nid" value="{{ data.transaction.nid   }}">
    <div class="form-row">
        <div class="form-group">
            <label>TRANSACTION DATE</label>
            <input type="text" id="transaction_date" name="transaction_date" readonly disabled value="{{ data.transaction.transaction_date }}"/>
        </div>
        <div class="form-group">
            <label>SERIAL NO.</label>
            <input type="number" id="sl_no" name="sl_no" readonly disabled value="{{ data.transaction.sl_no }}"/>
        </div>
        <div class="form-group">
            <label>RECEIPT NO.</label>
            <input type="number" id="receipt_no" name="receipt_no" readonly disabled value="{{ data.transaction.receipt_no }}"/>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label>PATIENT CODE</label>
            <input type="text" id="patient_code" name="patient_code" value="{{ data.transaction.patient_code }}"/>
        </div>
        <div class="form-group">
            <label>PATIENT</label>
            <input type="text" id="patient" name="patient" readonly disabled value="{{ data.transaction.patient }}"/>
        </div>
        <div class="form-group">
            <label>DOCTOR</label>
            <select name="doc" id="doc"></select>
        </div>
        <div class="form-group">
            <label>PRESCRIPTION NO.</label>
            <input type="number" id="prescription_number" name="prescription_number" value="{{ data.transaction.prescription_number }}"/>
        </div>
    </div>

    {% set i = 1 %}
    {% for key,service in data.services %}
        <div class="form-row">
            <div class="form-group">
                <label>Service Name</label>
                <input type="hidden" id="service_id_{{ i }}" value="{{ service.id }}" readonly />
                <input type="text" id="service_name_{{ i }}" name="service_name" value="{{ service.service_name }}" readonly tabindex="-1" />
            </div>
            <div class="form-group">
                <label>Base Amount</label>
                <input type="number" id="base_amount_{{ i }}" name="base_amount" value="{{ service.base_amount }}" onchange="countChange({{ i }})" />
            </div>
            <div class="form-group">
                <label>Count</label>
                <input type="number" id="service_count_{{ i }}" name="service_count" value="{{ service.count }}" min="1" onchange="countChange({{ i }})"/>
            </div>
            <div class="form-group">
                <label>Amount</label>
                <input type="number" id="service_amount_{{ i }}" name="service_amount" value="{{ service.amount }}" readonly tabindex="-1"/>
            </div>
        </div>
        {% set i = i+1 %}
    {% endfor %}

    <div class="form-row">
        <div class="form-group">
            <label>AMOUNT</label>
            <input type="number" id="amount" name="amount" value="{{ data.transaction.amount }}" readonly tabindex="-1"/>
        </div>
        <div class="form-group">
            <label>OLD DUE</label>
            <input type="number" id="old_due" name="old_due" value="0" readonly tabindex="-1"/>
        </div>
        <div class="form-group">
            <label>TOTAL</label>
            <input type="number" id="total" name="total" value="0" readonly tabindex="-1"/>
        </div>
        <div class="form-group">
            <label>CASH PAID</label>
            <input type="number" id="cash_paid" name="cash_paid" value="{{ data.transaction.cash_paid }}" onchange="cash_paidChange()"/>
        </div>
        <div class="form-group">
            <label>DUE</label>
            <input type="number" id="due" name="due" value="{{ data.due }}" readonly tabindex="-1"/>
        </div>
        <div class="form-group">
            <button style="margin-top: 22px; height: 25px" onclick="updateClicked(event)">UPDATE AMOUNTS</button>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label>BLOOD SUGAR FASTING</label>
            <input type="text" id="blood_sugar_fasting" name="blood_sugar_fasting" value="{{ data.transaction.blood_sugar_fasting }}"/>
        </div>
        <div class="form-group">
            <label>BLOOD SUGAR PP</label>
            <input type="text" id="blood_sugar_pp" name="blood_sugar_pp" value="{{ data.transaction.blood_sugar_pp }}"/>
        </div>
        <div class="form-group">
            <label>BLOOD SUGAR RANDOM</label>
            <input type="text" id="blood_sugar_random" name="blood_sugar_random" value="{{ data.transaction.blood_sugar_random }}"/>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label>BLOOD PRESSURE</label>
            <input type="text" id="blood_pressure" name="blood_pressure" value="{{ data.transaction.blood_pressure }}"/>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label>NARRATION</label>
            <textarea id="narration" name="narration">{{ data.transaction.narration }}</textarea>
        </div>
    </div>
    <input type="hidden" id="services" value="" name="services">
    <input type="hidden" id="patient_id" name="patient_id" value="{{ data.transaction.patient_id }}"/>
    <div class="form-row" style="border: none">
        <div class="form-group">
            <button onclick="formSubmit(event)">Update Slip</button>
        </div>
    </div>
</form>
<script>
    let clickedUpdate = false;
    window.onload = function () {

        let due = parseInt(document.getElementById('due').value);
        let cash_paid = parseInt(document.getElementById('cash_paid').value);
        let amount = parseInt(document.getElementById('amount').value);
        let total = due+cash_paid;
        let old_due = total-amount;
        document.getElementById('total').value = total;
        document.getElementById('old_due').value = old_due;
        getDoctorsList();

    };

    function countChange(i) {
        let base_amount = parseInt(document.getElementById('base_amount_'+i).value);
        let count = parseInt(document.getElementById('service_count_'+i).value);
        document.getElementById('service_amount_'+i).value = base_amount*count;
    }
    
    function updateClicked(e) {
        e.preventDefault();
        let c = {{ i }} - 1;
        let amount = 0;

        let services = [];

        for(let i = 1;i<=c;i++) {
            amount += parseInt(document.getElementById('service_amount_' + i).value);

            services[i-1] = {};
            services[i-1].nid = parseInt(document.getElementById('service_id_' + i).value);
            services[i-1].base_amount = parseInt(document.getElementById('base_amount_' + i).value);
            services[i-1].count = parseInt(document.getElementById('service_count_' + i).value);
            services[i-1].amount = parseInt(document.getElementById('service_amount_' + i).value);

        }

        document.getElementById('services').value = JSON.stringify(services);

        document.getElementById('amount').value = amount;
        document.getElementById('total').value = amount + parseInt(document.getElementById('old_due').value);

        let due = parseInt(document.getElementById('total').value) - parseInt(document.getElementById('cash_paid').value);
        if(due>=0)
            document.getElementById('due').value = due;

        clickedUpdate = true;
    }

    function cash_paidChange() {
        let due = parseInt(document.getElementById('total').value) - parseInt(document.getElementById('cash_paid').value);
        if(due>=0)
            document.getElementById('due').value = due;
    }

    function formSubmit(e){
        e.preventDefault();
        if(clickedUpdate){
            jQuery(".login-loader").addClass("is-active");
            document.getElementById('edit-form').submit();
        }
        else {
            alert("Amounts Not Updated");
        }
    }

    $(function () {

        $.get("get-patient-codes", function (data, status) {

            $("#patient_code").autocomplete({
                source: data,
                select: function () {
                    setTimeout(function () {
                        var id = $("#patient_code").val();
                        id = id.substring(0, id.indexOf("-") - 1);
                        $("#patient_code").val(id);
                    }, 5);
                    setTimeout(function () {
                        getPatient();
                    }, 10);
                }
            })

        });

    });

    function getPatient() {
        var id = jQuery("#patient_code").val();
        jQuery.get("get-patient-details?id=" + id, function (data, status) {

            if (data['patient_id'] == null) {
                alert('Invalid Patient Code');
            }
            else {
                jQuery('#patient').val(data['patient_name']);
                jQuery('#patient_id').val(data['patient_id']);
            }
        });
    }

    function getDoctorsList() {

        jQuery.get("get-doctors-list", function (data, status) {
            var optionsAsString = "";
            jQuery.map(data, function (item, index) {
                optionsAsString += "<option value='" + index + "'>" + item + "</option>";
            });
            console.log(optionsAsString);
            jQuery('#doc').append(optionsAsString);
            jQuery('#doc').val({{ data.transaction.doc_id }});
            jQuery(".login-loader").removeClass("is-active");

        });
    }
    
</script>

web/modules/custom/charges_slip/templates/patient-list.html.twig
<h1>Hello World</h1>